### ISSUE TITLE
Regex in search box (text filter)

### ISSUE THREAD

**Issue by joegoldin** [davidhu2000/kube-knots#280]
### Description

I'd to be able to filter resources by a regex.

For example, `matchmaker|game-play` would return results for matchmaker-service and game-play-service, etc.

### Use Cases

Filtering by resource name rather than namespace

### Would you be interestined in implementing this feature yourself?

- [ ] Yes, I am interested in implementing this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidhu2000** [comment]
this feature will be released on v0.0.44. thanks for the suggestion
